services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ai_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - ai-network

volumes:
  postgres_data:
  backups:

networks:
  ai-network:
    driver: bridge
